
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SentimentModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
            {
                Col0 = Console.ReadLine(),
            };
            SentimentModel.ModelInput sampleData1 = new SentimentModel.ModelInput()
            {
                Col0 = Console.ReadLine(),
            };
            SentimentModel.ModelInput sampleData2 = new SentimentModel.ModelInput()
            {
                Col0 = Console.ReadLine(),
            };
            
            // Make a single prediction on the sample data and print results
            var predictionResult = SentimentModel.Predict(sampleData);
            var predictionResult1 = SentimentModel.Predict(sampleData1);
            var predictionResult2 = SentimentModel.Predict(sampleData2);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");


            Console.WriteLine($"Col0: {@"Wow... Loved this place."}");
            Console.WriteLine($"Col1: {1F}");


            Console.WriteLine($"\n\nPredicted Col1: {predictionResult.Prediction}\n\n");
            Console.WriteLine($"\n\nPredicted Col1: {predictionResult1.Prediction}\n\n");
            Console.WriteLine($"\n\nPredicted Col1: {predictionResult2.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
